version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python app.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db
  
  
  db:
    image: mariadb:10.4.22
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: localhost
    ports:
      - "3307:3306"